version: "3.9"

services:
  vote:
    image: 682791326537.dkr.ecr.us-east-1.amazonaws.com/lks-voting-image:vote-dev-latest
    ports:
      - 80:80
    networks:
      - frontend
    deploy:
      replicas: 1

  result:
    image: 682791326537.dkr.ecr.us-east-1.amazonaws.com/lks-voting-image:result-dev-latest
    ports:
      - 81:80
    networks:
      - backend
    deploy:
      replicas: 1

  worker:
    image: 682791326537.dkr.ecr.us-east-1.amazonaws.com/lks-voting-image:worker-dev-latest
    networks:
      - frontend
      - backend
    deploy:
      replicas: 1

networks:
  frontend:
  backend:
